ApiVersion: v1
kind: Service
metadata:
  name: nservice
  labels:
    owner: macarious
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: nodejs