apiVersion: v1
kind: Namespace
metadata:
  name: mac
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndeployapp
  namespace: mac
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: macarious25siv/project:NodeV5
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb://nservicedb.mac.svc.cluster.local:27017/test"
---
apiVersion: v1
kind: Service
metadata:
  name: nserviceapp
  namespace: mac
spec:
  selector:
    app: nodejs
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30225

##-----------------------------------DB-----------------------------------
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: mac
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  # volumeMode: Filesystem
  # selector:
  #   matchLabels:
  #     type: mongodb
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndeploydb
  namespace: mac
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      labels:
        tier: db
    spec:
      containers:
        - name: mongodb
          image: mongo:4
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: db-volume
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: mypvc
---
apiVersion: v1
kind: Service
metadata:
  name: nservicedb
  namespace: mac
spec:
  selector:
    tier: db
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
---
