apiVersion: v1
kind: Namespace
metadata:
  name: mac

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndeploy
  labels:
    owner: mac
  namespace: mac
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: mongodb
          image: mongo:4
          ports:
            - containerPort: 27017
        - name: nodejs
          image: macarious25siv/project:NodeV5
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/test"

---

apiVersion: v1
kind: Service
metadata:
  name: nservice
  namespace: mac
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: nodejs
---
