apiVersion: v1
kind: Namespace
metadata:
  name: mac

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndeploy
  labels:
    owner: mac
  namespace: mac
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: mongodb
          image: mongo:4
          ports:
            - containerPort: 27017
        - name: nodejs
          image: macarious25siv/project:NodeV5
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/test"

---

apiVersion: v1
kind: Service
metadata:
  name: nservice
  namespace: mac
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30225
      protocol: TCP
  selector:
    app: nodejs
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-v1
  labels:
    app: hello
    version: v1
  namespace: mac
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
      version: v1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      containers:
        - name: hello-app
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: hello
  namespace: mac
spec:
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: mac
spec:
  rules:
    - host: mac.local
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: nservice
              port:
                number: 5000
        - path: "/api"
          pathType: Prefix
          backend:
            service:
              name: api
              port:
                number: 8080