version: '3.9'

services:
  app:
    image: macarious25siv/project:NodeV0
    container_name: node_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - Frontend

  mongodb:
    image: mongo:4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d  # Add this line
    networks:
      - Frontend

  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb_exporter
    # environment:
    #   - MONGODB_URI=mongodb://test:testing@mongodb:27017/admin
    environment:
        - MONGODB_URI=mongodb://test:testing@mongodb:27017/admin
    command:
      - '--collect-all'

    ports:
      - "9216:9216"
    depends_on:
      - mongodb
    restart: always  # Add this
    networks:
      - Frontend

  

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  Frontend:
    name: Frontend
    driver: bridge
