version: '3.9'

services:
  app:
    image: macarious25siv/project:NodeV0
    container_name: node_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:4
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge