version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "5000:5000"
    depends_on:
       mongodb:
        condition: service_healthy
    networks:
      - app-network

  mongodb:
    image: mongo:4
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge