# ----------- STAGE 1: Build Dependencies -----------

FROM node:18-slim AS builder
WORKDIR /app
COPY ./src/package*.json ./
RUN npm ci
COPY ./src .

# ----------- STAGE 2: Final Runtime Image -----------
FROM node:18-slim 
WORKDIR /app
COPY --from=builder /app /app
RUN groupadd -r nonrootgroup && useradd -r -g nonrootgroup -m nonrootuser && \
    npm ci --omit=dev && \
    npm cache clean --force && \
    chown -R nonrootuser:nonrootgroup /app
USER nonrootuser
EXPOSE 5000
ENTRYPOINT ["npm"]
CMD ["start"]
