{
 "title": "Mongodb_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Main Read_Write Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average read latency per collection",
   "type": "timeseries",
   "description": "This tells you how long your reads take on average for each collection.",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(mongodb_collstats_latencyStats_reads_latency[5m])\r\n/\r\nrate(mongodb_collstats_latencyStats_reads_ops[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache write throughput",
   "type": "timeseries",
   "description": "This gives you the rate of bytes written per second over the last 5 minutes",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_wt_cache_bytes_written_from_cache[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Queries (Workload Hotspots)",
   "type": "piechart",
   "description": "It tells you which collections are consuming the most operation time.\nGood to spot hotspots.",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_top_total_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "description": "The current size of cache in bytes.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "mongodb_ss_wt_cache_bytes_currently_in_the_cache{instance=\"mongodb_exporter:9216\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\"}",
     "legendFormat": "{{conn_type}}"
    },
    {
     "expr": "mongodb_ss_connections{conn_type=\"available\"}",
     "legendFormat": "{{conn_type}}"
    },
    {
     "expr": "mongodb_ss_connections{conn_type=\"totalCreated\"}",
     "legendFormat": "{{conn_type}}"
    },
    {
     "expr": "mongodb_ss_connections{conn_type=\"active\"}",
     "legendFormat": "{{conn_type}}"
    }
   ]
  }
 ]
}