version: '3.9'

services:
  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-proxy-network

  app:
    image: macarious25siv/project:NodeV0
    container_name: node_app
    depends_on:
      - mongodb
    networks:
      - app-proxy-network
      - app-db-network

  mongodb:
    image: mongo:4
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-db-network

volumes:
  mongodb_data:
    name: mongodb_data


networks:
  app-db-network:
    name: app-db-network
    driver: bridge
  app-proxy-network:
    name: app-proxy-network
    driver: bridge