# # ----------- STAGE 1: Build Dependencies -----------

# FROM node:18-slim AS builder
# WORKDIR /app
# COPY ./package*.json ./
# RUN npm ci
# COPY /src .

# # ----------- STAGE 2: Final Runtime Image -----------
# FROM node:18-slim 
# WORKDIR /app
# COPY --from=builder /app /app
# RUN groupadd -r nonrootgroup && useradd -r -g nonrootgroup -m nonrootuser && \
#     npm ci --omit=dev && \
#     npm cache clean --force && \
#     chown -R nonrootuser:nonrootgroup /app
# USER nonrootuser
# EXPOSE 5000
# ENTRYPOINT ["npm"]
# CMD ["start"]
    

FROM node:18
WORKDIR /app
COPY ../app/src/package.json .
RUN npm install
COPY ../app/src .
EXPOSE 5000
ENTRYPOINT ["npm"]
CMD ["start"]
