global:
  scrape_interval: 15s 
  evaluation_interval: 15s 
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "mongodb_exporter"
    static_configs:
      - targets: ["mongodb_exporter:9216"]
        labels:
          app: "mongodb_exporter"

  - job_name: "node_app"
    static_configs:
      - targets: ["node_app:5000"]
        labels:
          app: "node_app"
