apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      labels:
        tier: db
    spec:
      containers:
        - name: mongodb
          image: mongo:4
          ports:
            - containerPort: 27017



---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    tier: db
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
